create or replace TYPE CUST_RISQ_SOUV_REPORT AS OBJECT
(
    FUT_LIBELLE VARCHAR(200),
    FUT_ID VARCHAR(200),
    FUT_ID_UND VARCHAR(200),
    -- FUT_SECTION VARCHAR(200),
    FUT_SOUS_SECTION VARCHAR(200),
    FUT_MTM_EURO DECIMAL,
    FUT_QUANT DECIMAL,
    FUT_ECHEANCE VARCHAR(200),
    FUT_NOMINAL INTEGER,
    FUT_DEVISE VARCHAR(200),
    FUT_PRIX DECIMAL, 
    BOND_LIBELLE VARCHAR(200),
    BOND_NOMINAL DECIMAL, 
    BOND_COURU DECIMAL, 
    BOND_DEVISE VARCHAR(200),
    BOND_PRIX VARCHAR(200),
    BOND_PRIX_TYPE VARCHAR(200), 
    BOND_EMETTEUR VARCHAR(200),
    BOND_SENIORITY VARCHAR(200),
    AGGREGATED_RHO_EURO DECIMAL
);