SET SERVEROUTPUT ON SIZE 1000000;
SET DEFINE ON;
SET PAGESIZE 0;
SET LINESIZE 11000;
SET FEEDBACK OFF
SET TRIMSPOOL ON
SET HEADING OFF
SET TERMOUT OFF
set MARKUP csv ON quote off

/* extraction of RISQUES SOUVERAINS Report  */

exec PACK_REP_BATCH.PISTE_AUDIT('I', 'SEND_RISQUES_SOUVERAINS_REPORT', 'Start Risques Souverains extraction', '', 'RISQUES_SOUVERAINS_REPORT');
COMMIT;

SPOOL '&1'

select 'FUT_LIBELLE;FUT_ID;FUT_ID_UND;FUT_SECTION;FUT_SOUS_SECTION;FUT_MTM_EURO;FUT_QUANT;FUT_ECHEANCE;FUT_NOMINAL;FUT_DEVISE;FUT_PRIX;BOND_LIBELLE;BOND_NOMINAL;BOND_COURU;BOND_DEVISE;BOND_PRIX;BOND_PRIX_TYPE;BOND_EMETTEUR;BOND_SENIORITY;AGGREGATED_RHO_EURO' from dual;

select FUT_LIBELLE || ';' || FUT_ID || ';' || FUT_ID_UND || ';' || FUT_SECTION || ';' || FUT_SOUS_SECTION || ';' || FUT_MTM_EURO || ';' || FUT_QUANT || ';' || FUT_ECHEANCE || ';' || FUT_NOMINAL || ';' || FUT_DEVISE || ';' || FUT_PRIX || ';' || BOND_LIBELLE || ';' || BOND_NOMINAL || ';' || BOND_COURU || ';' || BOND_DEVISE || ';' || BOND_PRIX || ';' || BOND_PRIX_TYPE || ';' || BOND_EMETTEUR || ';' || BOND_SENIORITY || ';' || AGGREGATED_RHO_EURO from table(PACK_REP_BATCH_RISQ_SOUV.EXTRACT_RISQ_SOUV_REPORT);

SPOOL OFF

exec PACK_REP_BATCH.PISTE_AUDIT('I', 'SEND_RISQUES_SOUVERAINS_REPORT', 'Finish Risques Souverains extraction', '', 'RISQUES_SOUVERAINS_REPORT');
COMMIT;

SET TERMOUT ON
QUIT